#!/bin/bash
	#............................................. pstins script May 31 2017

	#....................................................................................... Install packages with pacman 
 	pacman -Syu  xorg-server  xorg-xinit  xterm xorg-fonts  xorg-twm virtualbox-guest-utils\
		     virtualbox-guest-modules-arch  linux-headers  polkit  ttf-liberation\
		     i3-wm i3-blocks i3-gaps lightdm lightdm-gtk-greeter rofi termite htop thunar\
		     thunar-volman gvfs  sudo  vim

set -x
	cp /etc/X11/xinit/xinitrc /home/beardo/.xinitrc
						       #......................................... Copy xinitrc to ~/
	cp /etc/X11/xinit/xserverrc /home/beardo/.xserverrc
							   #..................................... Copy xserverrc to ~/

	sed -i '/twm/s/^/#/g' /home/beardo/.xinitrc
	sed -i '/xclock/s/^/#/g' /home/beardo/.xinitrc
	sed -i '/xterm/s/^/#/g' /home/beardo/.xinitrc
						    #............................................ Comment out lines in ~/.xinitrc
	sed -i '/exec/s/^/#/g' /home/beardo/.xserverrc
						      #.......................................... Comment out line in ~/.xserverrc
	sed -i '/End/s/^/#/g' /etc/hosts
					  #...................................................... Comment out line in /etc/hosts
	echo 'exec i3' >> /home/beardo/.xinitrc
								      #.......................... Append line to ~/.xinitrc
	echo 'exec /usr/bin/Xorg -nolisten tcp "$@" vt$XDG_VTNR' >> /home/beardo/.xserverrc
											  #...... Append line to ~/.xserverrc
	echo '# End of file' >> /etc/hosts
					    #.................................................... Append line to /etc/hosts
	nano /home/beardo/.xinitrc
				 #............................................................... Check ~/.xinitrc
	nano /home/beardo/.xserverrc
				   #............................................................. Check ~/.xserverrc
	nano /etc/hosts
			#........................................................................ Check /etc/hosts
 	sed -i '/%wheel ALL=(ALL) ALL/s/^#//' /etc/sudoers
							    #.................................... Set up wheel for sudo 
	EDITOR=nano visudo
			    #..................................................................... Check suoders file

	chown beardo /home/beardo/.xinitrc
					 #........................................................ Ch owner of ~/.xinitrc to beardo
  	chown beardo /home/beardo/.xserverrc
					   #...................................................... Ch owner of ~/.xserverrc to beardo
	systemctl enable NetworkManager.service
	systemctl enable lightdm.service
	                                   #......................................................start networking and lightdm daemons
set +x

